### ISSUE TITLE
Tests laufen nicht "headless" gegen den Development-Server wegen fehlender Fixture

### ISSUE THREAD

**Issue by cgawron** [fhswf/openai-ui#18]
Wenn ich den Development-Server mit `npm start` starte und dann die Tests gegen Chrome laufen lasse (`npm run test:e2e`), bekomme ich folgende Fehler:

```
  1) User Interface
       Check the headline:
     CypressError: Timed out retrying after 4000ms: The command was expected to run against origin `http://localhost:5173` but the application is at origin `https://www.ki.fh-swf.de`.

This commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.

Using `cy.origin()` to wrap the commands run on `https://www.ki.fh-swf.de` will likely fix this issue.

`cy.origin('https://www.ki.fh-swf.de', () => {`
`  <commands targeting https://www.ki.fh-swf.de go here>`
`})`

https://on.cypress.io/cy-visit-succeeded-but-commands-fail
      at cypressErr (http://localhost:5173/__cypress/runner/cypress_runner.js:75257:18)
      at Object.errByPath (http://localhost:5173/__cypress/runner/cypress_runner.js:75312:10)
      at Object.commandCanCommunicateWithAUT (http://localhost:5173/__cypress/runner/cypress_runner.js:145351:90)
      at Array.<anonymous> (http://localhost:5173/__cypress/runner/cypress_runner.js:132218:22)
      at $Cy.getSubjectFromChain (http://localhost:5173/__cypress/runner/cypress_runner.js:138886:34)
      at $Cy.subject (http://localhost:5173/__cypress/runner/cypress_runner.js:138840:17)
      at Object.subjectFn (http://localhost:5173/__cypress/runner/cypress_runner.js:144150:28)
      at $Cy.verifyUpcomingAssertions (http://localhost:5173/__cypress/runner/cypress_runner.js:143498:31)
      at onRetry (http://localhost:5173/__cypress/runner/cypress_runner.js:144145:15)
      at tryCatcher (http://localhost:5173/__cypress/runner/cypress_runner.js:1807:23)
      at Promise.attempt.Promise.try (http://localhost:5173/__cypress/runner/cypress_runner.js:4315:29)
      at whenStable (http://localhost:5173/__cypress/runner/cypress_runner.js:144032:68)
      at <unknown> (http://localhost:5173/__cypress/runner/cypress_runner.js:143973:14)
      at tryCatcher (http://localhost:5173/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:5173/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (http://localhost:5173/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (http://localhost:5173/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (http://localhost:5173/__cypress/runner/cypress_runner.js:1701:18)
      at Promise._fulfill (http://localhost:5173/__cypress/runner/cypress_runner.js:1645:18)
      at <unknown> (http://localhost:5173/__cypress/runner/cypress_runner.js:5450:46)
  From Your Spec Code:
      at Context.eval (webpack://openai-ui/./cypress/e2e/uiTest.cy.js:12:36)
```

Dies liegt wahrscheinlich daran, dass die Weiterleitung zur Login-Seite nicht mittels Fixture abgefangen wird.

**Comment by cgawron** [comment]
In `beforeEach()` gehört folgendes hinein:

```JavaScript
    cy.fixture("user").then((user) => {
      cy.intercept("https://openai.ki.fh-swf.de/api/user", user).as("getUser");
    })

    cy.visit("http://localhost:5173/");
    cy.wait("@getUser");
```

**Comment by cgawron** [comment]
Hm, sehe gerade, dass das schon "drin" war. Offenbar habe ich nicht gepullt ...
